### ISSUE TITLE
Export Theme.kt from the sample app

### ISSUE THREAD

**Issue by Nek-12** [jordond/MaterialKolor#185] opened 2024-07-13 10:10 UTC
It would be great to be able to visit the sample app and export the theme as a kotlin file to statically embed it in the app, just like with the (abandoned and buggy) https://github.com/material-foundation/material-theme-builder. In that case, the library would serve  as a modern, working replacement for those who just want to build a static theme and serve a double purpose.

**Comment by jordond** [comment] 2024-09-19 00:18
duplicate of #73

**Closed by jordond** 2024-09-19 00:18 UTC

**Comment by jordond** [comment] 2024-10-01 23:59
I have just released the first version of [MaterialKolor Builder](https://github.com/jordond/materialkolorbuilder)! Check it out at [materialkolor.com](https://materialkolor.com).
