### ISSUE TITLE
Plug in custom color hex in the demo app 

### ISSUE THREAD

**Issue by Nek-12** [jordond/MaterialKolor#187] opened 2024-07-13 15:33 UTC
https://demo.materialkolor.com/ allows only a predefined selection of colors. I'd like to enter my own hex color

**Comment by jordond** [comment] 2024-09-19 00:18
duplicate of #73

**Closed by jordond** 2024-09-19 00:18 UTC
Labels: good first issue

**Comment by jordond** [comment] 2024-10-01 23:59
I have just released the first version of [MaterialKolor Builder](https://github.com/jordond/materialkolorbuilder)! Check it out at [materialkolor.com](https://materialkolor.com).
